server.port: 8181

logging.level.com.sivalabs: debug

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://192.168.99.100:3306/catalog?useSSL=false"
    username: root
    password: admin
    initialization-mode: always

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

# expose all the Actuator endpoints
management.endpoints.web.exposure.include: "*"
